### ISSUE TITLE
pip install restorething

### ISSUE THREAD

**Issue by ghost** [madmickstar/restorething#2]
installing restorething via pip ends up in error, bellow are logs from pip
```
user@machine:~$ pip install restorething
Collecting restorething
  Downloading restorething-0.2.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-6c5cvgu8/restorething/setup.py", line 4, in <module>
        import restorething
      File "/tmp/pip-build-6c5cvgu8/restorething/restorething/__init__.py", line 2, in <module>
        from _version import __version__
    ImportError: No module named '_version'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-6c5cvgu8/restorething/
```

**Comment by madmickstar** [comment]
Apologies for the delayed response. 

Can you advise python version and OS flavor and version?
