### ISSUE TITLE
Issue with file path containing non ascii characters

### ISSUE THREAD

**Issue by wagonli** [madmickstar/restorething#3]
I ran in to an issue with a certain file path (no idea which one).
This is the error output :

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/wagonli/.local/lib/python2.7/site-packages/restorething/__main__.py", line 16, in <module>
    main()
  File "/home/wagonli/.local/lib/python2.7/site-packages/restorething/__main__.py", line 12, in main
    restorething.main()
  File "/home/wagonli/.local/lib/python2.7/site-packages/restorething/restorething.py", line 214, in main
    dbrestore.main(database_file, cli_epoch, restdir_abs_path, args)
  File "/home/wagonli/.local/lib/python2.7/site-packages/restorething/dbrestore.py", line 296, in main
    restore_file(final_results, restdir_abs_path, args)
  File "/home/wagonli/.local/lib/python2.7/site-packages/restorething/dbrestore.py", line 163, in restore_file
    dst_dir = process_dir(final_results, restdir_abs_path, args.no_sim)
  File "/home/wagonli/.local/lib/python2.7/site-packages/restorething/dbrestore.py", line 191, in process_dir
    if not os.path.exists(dst_dir):
  File "/usr/lib/python2.7/genericpath.py", line 26, in exists
    os.stat(path)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 64: ordinal not in range(128)
```

https://stackoverflow.com/questions/19833440/unicodeencodeerror-ascii-codec-cant-encode-character-u-xe9-in-position-7#19833471

Seems to point out the way to work around this (unfortunately i'm totally noob to python so I won't be able to create a merge request)

**Comment by wagonli** [comment]
From what I see in `dbrestore.py` line 188 we can fix this by doing 

`dst_dir = os.path.join(rest_dir, cleaned_path).encode('utf8')`
